### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by rilmasaker** [flsy/react-mapycz#195]
After `npm i react-mapycz`

```
import { Map, MarkerLayer, Marker } from 'react-mapycz';
const TestMap = () => (

  <Map center={{ lat: 55.604890000000005, lng: 8.97171 }}>
    <MarkerLayer>
      <Marker coords={{ lat: 55.60501000000001, lng: 8.97171 }} />
      <Marker coords={{ lat: 55.547290000000004, lng: 8.897590000000001 }} />
    </MarkerLayer>
  </Map>
);
```

`Uncaught ReferenceError: module is not defined`
`Uncaught TypeError: SMap._ is not a function`
![image](https://user-images.githubusercontent.com/48757870/110837950-2dd24580-82a2-11eb-9d26-5da2a77bb6df.png)

I work in Meteor.js but I think it shouldn't matter.
Do I have to load the script from api.map.cz somewhere?
A little more documentation will be welcome :)  , even more so as the documentation of map.cz is in Czech

**Comment by kolebjak** [comment]
Hi, this library should work out of the box - no extra scripts needed.

**Comment by kolebjak** [comment]
I'll try to run it in Meteor and let you know.

**Comment by rilmasaker** [comment]
I added you to the simple repo

**Comment by kolebjak** [comment]
@rilmasaker After an investigation it looks like a Meteor problem. IMO the problem is that our library calls a 3rd party loader script (mapycz loader) which contains `... { module.exports = G; }` and meteor does have a problem with module exports for some reason. 
Unfortunately i'm not experienced enough with Meteor to provide a solution, but i can confirm that this library works with React / Webpack (tested on Create React App).
